friender/src/booking_service/urls.py
from django.urls import URLPattern, path
from .views import (DeleteBookingView, AddGuestView, GuestDeleteView, GuestListView, book_room_view,
                    check_room_availability_view,
                    HomeView, custom_login_view, custom_logout_view, custom_register_view, hotel_view,
                    hotels_view, users_view)


urlpatterns: list[URLPattern] = [
    #  path('', home_view, name='home'),
    path('', HomeView.as_view(), name='home'),
    path('hotels', hotels_view, name='hotels'),
    path('hotels/<str:hotel_name>', hotel_view, name='hotel'),
    path('users', users_view, name='guest_list'),
    path('book/<str:hotel_name>/<int:user_id>/<int:room_number>/',
         book_room_view, name='book_room'),
    path('check_room_availability',
         check_room_availability_view, name='check_room'),
    path('delete_booking/<int:booking_id>/',
         DeleteBookingView.as_view(), name='delete_Booking'),
    path('add_guest', AddGuestView.as_view(), name='add_guest'),
    path('guest/<int:pk>/delete', GuestDeleteView.as_view(), name='guest_delete'),
    path('guests', GuestListView.as_view(), name='guest_list'),
    # re_path(r"^articles/(?P<year>[0-9]{4})/$", views.year_archive),

    path('register', custom_register_view, name='register'),
    path('login', custom_login_view, name='login'),
    path('logout', custom_logout_view, name='logout'),
]

friender/src/config/urls.py
from django.contrib import admin
from django.urls import URLResolver, include, path
from django.conf.urls import handler404

#todo добавление обработки медиа-файлов
from django.conf.urls.static import static
from config import settings

handler404 = 'booking_service.views.error_404_view'

urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('booking/', include('booking_service.urls')),
    path('api/v1/', include('booking_rest_api.urls')),
    path('auth/', include('booking_auth_api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friender/src/booking_service/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import FileExtensionValidator
from .validators import validate_doc_extension

SEX_CHOICES = [
    ("m", "male"),
    ("f", "female"),
]

ROOM_TYPE_CHOICES = [
    ("s", "single"),
    ("d", "double"),
    ("o", "other")
]


# Guest
# Profile
# Booking
# Hotel
# Room
# HotelService
# BookingService
# Comment




class Guest(models.Model):
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=50)
    age = models.PositiveIntegerField(validators=[
        MaxValueValidator(90),
        MinValueValidator(18)
    ])
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    email = models.EmailField(null=True)
    phone = PhoneNumberField(null=True, blank=False, unique=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['first_name'], name='first_name_idx'),
            models.Index(fields=['last_name'], name='last_name_idx'),
            models.Index(fields=['age'], name='age_idx'),
        ]

    # Для визуалиции объекта в shell
    def __str__(self):
        return f" {self.first_name} {self.last_name}"


class HotelOwner(Guest):
    owner_exp_status = models.IntegerField(null=True)


class Profile(models.Model):
    photo = models.ImageField(
        null=True, blank=True, verbose_name="User photo", upload_to="users_photo/")
    id_card = models.IntegerField(null=True)
    serial_number = models.CharField(null=True, max_length=30)
    guest = models.OneToOneField(
        Guest, on_delete=models.CASCADE, related_name="profile")
    info = models.FileField(
        null=True, blank=True, upload_to="profile_info/",
        validators=[FileExtensionValidator(allowed_extensions=['doc']), validate_doc_extension]
    )

    def __str__(self):
        return f"profile: {self.id_card}"


class Hotel(models.Model):
    name = models.CharField(max_length=50)
    stars = models.FloatField(validators=[
        MinValueValidator(0.0), MaxValueValidator(5.0)
    ])
    address = models.CharField(max_length=80)
    city = models.CharField(max_length=30)
    phone = PhoneNumberField(null=False, blank=False, unique=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(
        null=True, verbose_name="hotel_photo", upload_to="hotels_photo/", blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['name'], name='name_idx'),
            models.Index(fields=['stars'], name='stars_idx')
        ]

    def __str__(self):
        return f" {self.name} {self.city}"


class Room(models.Model):
    number = models.PositiveIntegerField(validators=[
        MaxValueValidator(1000),
        MinValueValidator(1)
    ])
    type = models.CharField(max_length=1, choices=ROOM_TYPE_CHOICES)
    price = models.FloatField()
    hotel = models.ForeignKey(
        Hotel, on_delete=models.SET_NULL, null=True, related_name="rooms")
    is_booked = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.number} | {self.hotel.name}'


class HotelComment(models.Model):
    text = models.CharField(max_length=200, null=True)
    time = models.DateTimeField(auto_now_add=True)
    hotel = models.ForeignKey(
        Hotel, on_delete=models.SET_NULL, null=True, related_name="comments")
    guest = models.ForeignKey(
        Guest, on_delete=models.SET_NULL, null=True, related_name="comments")

    # def __str__(self):
    #     return f"Guest: {self.guest.first_name} ||| comments: {self.text}"


class Booking(models.Model):
    room = models.ForeignKey(
        Room, related_name='bookings', on_delete=models.CASCADE, null=True)
    details = models.CharField(max_length=200, null=True)
    check_in_date = models.DateTimeField(null=True)
    check_out_date = models.DateTimeField(null=True)
    guest = models.ForeignKey(
        Guest, on_delete=models.SET_NULL, null=True, related_name='bookings')
    hotel = models.ForeignKey(
        Hotel, on_delete=models.SET_NULL, null=True, related_name='bookings')
    hotel_services = models.ManyToManyField(
        'HotelService', related_name='bookings')

    # def __str__(self):
    #     return f"Guest: {self.guest.first_name} ||| Hotel: {self.hotel.name}"


class HotelService(models.Model):
    hotel = models.ForeignKey(
        Hotel, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


class BookingService(models.Model):
    booking = models.ForeignKey(
        Booking, on_delete=models.CASCADE, related_name='services')
    service = models.ForeignKey(HotelService, on_delete=models.CASCADE)

    def __str__(self):
        return f"Booking id: {self.booking.id} ||| Service: {self.service.name}"


class Queue(models.Model):
    value = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.value)

friender/src/booking_service/views.py
from multiprocessing.managers import BaseManager
from typing import Optional
from django.db.models.manager import BaseManager
from django.utils import timezone
from datetime import timedelta
from django.shortcuts import redirect, render
from datetime import datetime
from django.db.models import Q
from django.views import View
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from .forms import AddCommentForm, AddGuestForm, CheckRoomForm, CustomAuthenticationForm, CustomUserCreationForm, ProfileForm
from .models import Booking, Guest, Hotel, HotelComment, Profile, Room
from django.db import transaction
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.base_user import AbstractBaseUser
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.cache import cache
from django.db.models import Prefetch
import logging

logger = logging.getLogger(__name__)

class HomeView(TemplateView):
    template_name: str = 'home.html'

# * login_required - доступ только для аутентифицированных в админке
# * permission_requiered - доступ только с правами для просмотра в админке


@permission_required("booking_service.hotels_view", login_url=reverse_lazy("login"))
@login_required(login_url=reverse_lazy("login"))
@cache_page(60 * 1)  # кэширование конкретной вьюшки на N минут
def hotels_view(request: HttpRequest) -> HttpResponse:
    print('Check cache hotels_view')
    hotels_with_comments = Hotel.objects.prefetch_related(
        # Prefetch - предварительная загрузка связанных объектов
        Prefetch('comments', queryset=HotelComment.objects.all())
    ).all()[:10]
    
    hotels_data = [
        {'hotel': hotel, 'comments': hotel.comments.all()}
        for hotel in hotels_with_comments
    ]

    context = {'hotels': hotels_data}

    return render(request=request, template_name='hotels.html', context=context)


def hotel_view(request: HttpRequest, hotel_name: str) -> HttpResponse:
    hotel: BaseManager[Hotel] = Hotel.objects.filter(name=hotel_name).first()

    if not hotel:
        return render(request=request, template_name='404.html')

    comments = HotelComment.objects.filter(hotel=hotel).select_related('guest')

    # Создание формы AddCommentForm, AddCommentForm наследуется от модели HotelComment
    if request.method == 'POST':
        comment_form = AddCommentForm(request.POST)
        if comment_form.is_valid():
             # костыль, предполагаем, что зарег пользователь в бд оставляет коммент
            guest = Guest.objects.get(
                first_name='Alice', last_name='Cooper'
            )
            new_comment = comment_form.save(commit=False)
            new_comment.guest = guest
            new_comment.hotel = hotel
            new_comment.save()
            return redirect('hotel', hotel_name=hotel_name)
    else:
        comment_form = AddCommentForm()

    # Формирование списка комментов
    # + исключение комментов удаленных пользователей
    comment_list = [{'name': comment.guest.first_name, 'text': comment.text} 
                    for comment in comments 
                    if comment.guest and comment.guest.first_name]

    context = {
        'hotel': hotel,
        'comments': comment_list,
        'comment_form': comment_form,
    }

    return render(request, 'hotel.html', context)

# * @permission_required("booking_service.hotels_view",login_url="/admin/login/"), в классах используем PermissionRequiredMixin
# * @login_required(login_url="/admin/login/"), в классах используем LoginRequiredMixin


def users_view(request: HttpRequest) -> HttpResponse:
    guests: BaseManager[Guest] = Guest.objects.all()
    guests_list = []

    for guest in guests:
        bookings: BaseManager[Booking] = Booking.objects.filter(
            guest_id=guest.id).prefetch_related('hotel_services')
        services_list = []
        for booking in bookings:
            for service in booking.hotel_services.all():
                services_list.append(service.name)
        guests_list.append({'guest': guest, 'services': services_list})

    context = {
        'guests': guests_list,
    }

    return render(request=request, template_name='users.html', context=context)


def book_room_view(request: HttpRequest, hotel_name: str, user_id: int, room_number: int) -> HttpResponse:
    context = {
        'hotel_name': hotel_name,
        'user_id': user_id,
        'room_number': room_number,
        'info': ''
    }

    try:
        hotel = Hotel.objects.get(name=hotel_name)
    except Hotel.DoesNotExist:
        context['hotel_name'] = 'Hotel is not found'
        return render(request, 'book.html', context)

    try:
        guest = Guest.objects.get(id=user_id)
    except Guest.DoesNotExist:
        context['user_id'] = 'User is not found'
        return render(request, 'book.html', context)

    try:
        room = Room.objects.get(hotel=hotel, number=room_number)
    except Room.DoesNotExist:
        context['room_number'] = 'Room is not found'
        return render(request, 'book.html', context)

    # транзакционное изменение
    with transaction.atomic():
        # проверка, есть ли актуальная бронь на данный номер в данном отеле
        # exists - проверяет наличие объектов в QuerySet, возвращает True\False
        if Booking.objects.filter(hotel=hotel, room=room).exists():
            context['info'] = f'hotel room: {str(room_number)} booked'
            return render(request, 'book.html', context)

        Booking.objects.create(
            guest=guest,
            hotel=hotel,
            room=room,
            details="Booking details from book_room_view",
            check_in_date=timezone.now(),
            check_out_date=timezone.now() + timedelta(days=7),  # +7 дней
        )
        room.is_booked = True
        room.save()

    return render(request, 'book.html', context)


# относится к check_room_availability_view
def render_check_room_view(request: HttpRequest, error: str = '') -> HttpResponse:
    form = CheckRoomForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'check_room_availability.html', context)

# относится к check_room_availability_view
def get_guest_by_full_name(full_name: str) -> Optional[Guest]:
    first_name, last_name = full_name.split()
    return Guest.objects.get(Q(first_name=first_name) & Q(last_name=last_name))

# относится к check_room_availability_view
def get_room_by_number_and_hotel(room_number: int, hotel_name: str) -> Room:
    return Room.objects.get(hotel__name=hotel_name, number=room_number)

# вьюшка проверки брони
def check_room_availability_view(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        # CheckRoomForm не связана с моделью
        check_room_form = CheckRoomForm(request.POST)
        if check_room_form.is_valid():
            room_number = int(request.POST.get('room_number'))
            hotel_name = request.POST.get('hotel')
            user_name = request.POST.get('guest')
            check_in_date = request.POST.get('check_in_date')
            check_out_date = request.POST.get('check_out_date')

            # Преобразование строк в datetime объекты
            check_in_date = datetime.strptime(check_in_date, '%Y-%m-%d')
            check_out_date = datetime.strptime(check_out_date, '%Y-%m-%d')

            try:
                guest: Guest | None = get_guest_by_full_name(user_name)
            except Guest.DoesNotExist:
                return render_check_room_view(request, error='User is not found')

            try:
                room: Room = get_room_by_number_and_hotel(
                    room_number, hotel_name)
            except:
                return render_check_room_view(request, error='Room is not found')

            try:
                hotel: Hotel = Hotel.objects.get(name=hotel_name)
            except Hotel.DoesNotExist:
                return render_check_room_view(request, error='Hotel is not found')

            is_room_booked: bool = Booking.objects.filter(
                hotel__name=hotel_name,
                room=room,
                check_in_date__lt=check_out_date,
                check_out_date__gt=check_in_date
            ).exists()

            if not is_room_booked:
                # транзакционный контекст для обеспечения атомарности операций
                with transaction.atomic():
                    Booking.objects.create(
                        guest=guest,
                        hotel=hotel,
                        room=room,
                        details="Booking details from check_room_availability_view",
                        check_in_date=check_in_date,
                        check_out_date=check_out_date,
                    )
                    room.is_booked = True
                    room.save()
                return render_check_room_view(request, error='Booking successful')
            else:
                return render_check_room_view(request, error='Unavailable')
    return render_check_room_view(request, error='')


def error_404_view(request, exception) -> HttpResponse:
    return render(request, '404.html', {})


class DeleteBookingView(View):
    template_name: str = 'delete_booking.html'

    def get(self, request: HttpRequest, booking_id: int) -> HttpResponse:
        context: dict[str, int] = {
            'booking_id': booking_id
        }
        try:
            with transaction.atomic():
                # select_for_update - блокировка записи бронирования

friender/src/templates/booking_service/add_guest.html
{% extends "base.html" %}
{% block title %}Friender | add Guest{% endblock %}

{% block content %}

<div class="container" style="margin-top: 150px;">
    <h2> Add Guest Form</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'add_guest' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <h2>Profile</h2>
        {{ profile_form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>



{% endblock %}

friender/src/templates/booking_service/add_hotel_comment.html
{% load crispy_forms_tags %}

<div class="container mt-5">
    <h2> Add comment</h2>
    <form method="post" action="{% url 'hotel' hotel_name=hotel.name %}">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button type="submit">Submit</button>
    </form>
</div>

friender/src/templates/booking_service/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Friender{% endblock %}</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
        integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" /> -->
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>

<body>
    {% include "header.html" %}
    <main class="main">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
    </footer>

    <!-- jQuery and jQuery UI -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Bootstrap JS -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script> -->

    <script>
        $(function () {
            $('#id_check_in_date, #id_check_out_date').datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
</body>

</html>

friender/src/templates/booking_service/book.html
{% extends 'base.html' %}

{% block title %}Book | Friender{% endblock %}

{% block content %}
<section style="margin-top: 50px;">
    <p>hotel_name: {{hotel_name}}</p>
    <p>user_id: {{user_id}}</p>
    <p>room_number: {{room_number}}</p>
    {% if info %}
    <p style="color: red;">info: {{info}}</p>
    {% endif %}
</section>
{% endblock %}

friender/src/templates/booking_service/check_room_availability.html
{% extends "base.html" %}
{% block title %}Friender{% endblock %}

{% block content %}


<div class="container" style="margin-top: 150px;">
    <h2> Check Room Form</h2>
    <form method="post" action="/booking/check_room_availability">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <p>error: {{error}}</p>
</div>

{% endblock %}

<!-- jQuery and jQuery UI -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!-- Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

friender/src/templates/booking_service/comments.html
{% load static %}
{% load cache %}

{% cache 20 comments %}
<section id="testimonials" class="testimonials section">
    <div class="container section-title" data-aos="fade-up">
        <h2>Comments</h2>
    </div>
    {% for comment in comments %}
    <div class="swiper-slide">
        <div class="testimonial-item">
            <img src="{% static 'img/profile.webp' %}" class="testimonial-img" alt="">
            <h3>{{ comment.name }}</h3>
            <p>
                <i class="bi bi-quote quote-icon-left"></i>
                <span>{{ comment.text }}</span>
                <i class="bi bi-quote quote-icon-right"></i>
            </p>
        </div>
    </div>
    {% endfor %}
</section>
{% endcache %}

friender/src/templates/booking_service/delete_booking.html
{% extends 'base.html' %}

{% block title %}Delete | Friender{% endblock %}

{% block content %}
<section style="margin-top: 50px;">
    <p>Book ID: {{booking_id}}</p>
    {% if info %}
    <p style="color: red;">info: {{info}}</p>
    {% endif %}
</section>
{% endblock %}

friender/src/templates/booking_service/guest_confirm_delete.html
{% extends 'base.html' %}
{% block title %} Delete Guest | Friender {% endblock %}

{% block content %}
  <h2>Are you sure you want to delete this guest?</h2>
  <p>{{ object.first_name }} {{ object.last_name }}</p>
  
  <form method="post">
      {% csrf_token %}
      <button type="submit">Yes, delete</button>
      <a href="{% url 'guest_list' %}">Cancel</a>
  </form>
{% endblock %}

friender/src/templates/booking_service/header.html
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">
      <a href="#" class="logo d-flex align-items-center me-auto">
        <h1 class="sitename">Friender</h1>
      </a>
      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'home' %}" class="">Home</a></li>
          <li><a href="{% url 'hotels' %}">Hotels</a></li>
          <li><a href="{% url 'guest_list' %}">Users</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
      <div style="margin-left: 150px;"><a href="{% url 'logout' %}">Logout</a></div>
    </div>

  </header>

friender/src/templates/booking_service/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home | Friender{% endblock %}

{% block content %}

<section id="hero" class="team section">
    <div class="container section-title" data-aos="fade-up">
    </div>
    <div class="container">
        <div class="row gy-4">
            <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center">
                <h1 class="">Home</h1>
                <p class="">Website with Python (Django, Django Rest Framework),  PostgreSQL</p>
            </div>
            <!-- <div class="col-lg-6 order-1 order-lg-2 hero-img">
                <img src="{% static 'img/hero-img.png' %}" class="img-fluid animated" alt="">
            </div> -->
        </div>
    </div>

</section>
{% endblock %}

friender/src/templates/booking_service/hotel.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Hotel | Friender{% endblock %}

{% block content %}
<section id="team" class="team section">
    <div class="container section-title" data-aos="fade-up">
        <h2>{{hotel.name}}</h2>
    </div>
    <div class="container">
        <div class="row gy-4">
            <div class="" data-aos="fade-up" data-aos-delay="100">
                <div class="team-member d-flex align-items-start">
                    <div class="pic"><img src="{% static 'img/hotel.jpeg' %}" class="img-fluid" alt=""></div>
                    <div class="member-info">
                        <h4>{{hotel.name}}</h4>
                        <span>Rating: {{hotel.stars}} </i></span>
                        <p>Phone: {{hotel.phone}}</p>
                        <p>City: {{hotel.city}}</p>
                        <p>Address: {{hotel.address}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% include "comments.html" %}
{% include "add_hotel_comment.html" %}
{% endblock %}

friender/src/templates/booking_service/hotels.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Hotels | Friender{% endblock %}

{% block content %}

<section id="team" class="team section">
    <div class="container section-title" data-aos="fade-up">
        <h2>Hotels</h2>
    </div>
    <div class="container">
        <div class="row gy-4">
            {% for item in hotels %}
            <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
                <div class="team-member d-flex align-items-start">
                    <div class="pic"><img src="{% static 'img/hotel.jpeg' %}" class="img-fluid" alt=""></div>
                    <div class="member-info">
                        <h4>{{item.hotel.name}}</h4>
                        <span>Rating: {{item.hotel.stars}} </i></span>
                        <p>Address: {{item.hotel.address}}</p>
                        <hr/>
                        <a href="{% url 'hotel' item.hotel.name %}">
                            <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-rounded btn-sm"
                                data-mdb-ripple-color="dark">See
                                profile</button>
                        </a>
                        <div class="container">
                            <br>
                            <h5>Comments</h5>
                            {% for comment in item.comments %}
                            {% if comment.guest.first_name %}
                            <p><b>{{comment.guest.first_name}}</b>: {{comment.text}}</p>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

friender/src/templates/booking_service/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login | Friender{% endblock %}

{% block content %}
<section id="team" class="team section">
    <div class="container" style="margin-top: 50px;">
        <h2>Login</h2>
        <form method="post" action="{% url 'login'%}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>

        <div>
             <a href="{% url 'register' %}" class="">registration</a>
        </div>
    </div>
</section>
{% endblock %}

friender/src/templates/booking_service/users.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users | Friender{% endblock %}

{% block content %}
<section id="team" class="team section">
    <div class="container section-title" data-aos="fade-up">
        <h2>Users</h2>
    </div>
    <div class="add_user_button_container">
        <a href="{% url 'add_guest' %}" class="btn btn-primary">Add user</a>
    </div>
    <div class="container">
        <div class="row gy-4">
            {% for item in guests %}
            <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
                <div class="team-member d-flex align-items-start">
                    <div class="pic">
                        {% if item.guest.profile and item.guest.profile.photo %}
                        <img src="{{ item.guest.profile.photo.url }}" class="img-fluid" alt="User Photo">
                        {% else %}
                        <img src="{% static 'img/user.avif' %}" class="img-fluid" alt="">
                        {% endif %}
                    </div>
                    <div class="member-info">
                        <h4>{{item.guest.first_name}} {{item.guest.last_name}}</h4>
                        <span>Age: {{item.guest.age}}</span>
                        {% if item.guest.email %}
                        <p>email: {{item.guest.email}}</p>
                        {% endif %}
                        {% for service in item.services %}
                        <p>{{service}}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}